<div id="quest_icon_picker_reveal" class="reveal-modal icon-picker-reveal">
   <h2>Icon</h2>
   <div class="edit-content">
      <h1>FontAwesome Icons</h1>
      <section id="web-application">
         <div class="row fontawesome-icon-list">
            <div class="fa-hover"><a href="#fa-adjust"><i class="fa fa-adjust"></i></a></div>
            <div class="fa-hover"><a href="#fa-anchor"><i class="fa fa-anchor"></i></a></div>
            <div class="fa-hover"><a href="#fa-archive"><i class="fa fa-archive"></i></a></div>
            <div class="fa-hover"><a href="#fa-area-chart"><i class="fa fa-area-chart"></i></a></div>
            <div class="fa-hover"><a href="#fa-arrows"><i class="fa fa-arrows"></i></a></div>
            <div class="fa-hover"><a href="#fa-arrows-h"><i class="fa fa-arrows-h"></i></a></div>
            <div class="fa-hover"><a href="#fa-arrows-v"><i class="fa fa-arrows-v"></i></a></div>
            <div class="fa-hover"><a href="#fa-asterisk"><i class="fa fa-asterisk"></i></a></div>
            <div class="fa-hover"><a href="#fa-at"><i class="fa fa-at"></i></a></div>
            <div class="fa-hover"><a href="#fa-car"><i class="fa fa-automobile"></i></a></div>
            <div class="fa-hover"><a href="#fa-ban"><i class="fa fa-ban"></i></a></div>
            <div class="fa-hover"><a href="#fa-university"><i class="fa fa-bank"></i></a></div>
            <div class="fa-hover"><a href="#fa-bar-chart"><i class="fa fa-bar-chart"></i></a></div>
            <div class="fa-hover"><a href="#fa-bar-chart"><i class="fa fa-bar-chart-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-barcode"><i class="fa fa-barcode"></i></a></div>
            <div class="fa-hover"><a href="#fa-bars"><i class="fa fa-bars"></i></a></div>
            <div class="fa-hover"><a href="#fa-bed"><i class="fa fa-bed"></i></a></div>
            <div class="fa-hover"><a href="#fa-beer"><i class="fa fa-beer"></i></a></div>
            <div class="fa-hover"><a href="#fa-bell"><i class="fa fa-bell"></i></a></div>
            <div class="fa-hover"><a href="#fa-bell-o"><i class="fa fa-bell-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-bell-slash"><i class="fa fa-bell-slash"></i></a></div>
            <div class="fa-hover"><a href="#fa-bell-slash-o"><i class="fa fa-bell-slash-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-bicycle"><i class="fa fa-bicycle"></i></a></div>
            <div class="fa-hover"><a href="#fa-binoculars"><i class="fa fa-binoculars"></i></a></div>
            <div class="fa-hover"><a href="#fa-birthday-cake"><i class="fa fa-birthday-cake"></i></a></div>
            <div class="fa-hover"><a href="#fa-bolt"><i class="fa fa-bolt"></i></a></div>
            <div class="fa-hover"><a href="#fa-bomb"><i class="fa fa-bomb"></i></a></div>
            <div class="fa-hover"><a href="#fa-book"><i class="fa fa-book"></i></a></div>
            <div class="fa-hover"><a href="#fa-bookmark"><i class="fa fa-bookmark"></i></a></div>
            <div class="fa-hover"><a href="#fa-bookmark-o"><i class="fa fa-bookmark-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-briefcase"><i class="fa fa-briefcase"></i></a></div>
            <div class="fa-hover"><a href="#fa-bug"><i class="fa fa-bug"></i></a></div>
            <div class="fa-hover"><a href="#fa-building"><i class="fa fa-building"></i></a></div>
            <div class="fa-hover"><a href="#fa-building-o"><i class="fa fa-building-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-bullhorn"><i class="fa fa-bullhorn"></i></a></div>
            <div class="fa-hover"><a href="#fa-bullseye"><i class="fa fa-bullseye"></i></a></div>
            <div class="fa-hover"><a href="#fa-bus"><i class="fa fa-bus"></i></a></div>
            <div class="fa-hover"><a href="#fa-taxi"><i class="fa fa-cab"></i></a></div>
            <div class="fa-hover"><a href="#fa-calculator"><i class="fa fa-calculator"></i></a></div>
            <div class="fa-hover"><a href="#fa-calendar"><i class="fa fa-calendar"></i></a></div>
            <div class="fa-hover"><a href="#fa-calendar-o"><i class="fa fa-calendar-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-camera"><i class="fa fa-camera"></i></a></div>
            <div class="fa-hover"><a href="#fa-camera-retro"><i class="fa fa-camera-retro"></i></a></div>
            <div class="fa-hover"><a href="#fa-car"><i class="fa fa-car"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-down"><i class="fa fa-caret-square-o-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-left"><i class="fa fa-caret-square-o-left"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-right"><i class="fa fa-caret-square-o-right"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-up"><i class="fa fa-caret-square-o-up"></i></a></div>
            <div class="fa-hover"><a href="#fa-cart-arrow-down"><i class="fa fa-cart-arrow-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-cart-plus"><i class="fa fa-cart-plus"></i></a></div>
            <div class="fa-hover"><a href="#fa-cc"><i class="fa fa-cc"></i></a></div>
            <div class="fa-hover"><a href="#fa-certificate"><i class="fa fa-certificate"></i></a></div>
            <div class="fa-hover"><a href="#fa-check"><i class="fa fa-check"></i></a></div>
            <div class="fa-hover"><a href="#fa-check-circle"><i class="fa fa-check-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-check-circle-o"><i class="fa fa-check-circle-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-check-square"><i class="fa fa-check-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-check-square-o"><i class="fa fa-check-square-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-child"><i class="fa fa-child"></i></a></div>
            <div class="fa-hover"><a href="#fa-circle"><i class="fa fa-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-circle-o"><i class="fa fa-circle-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-circle-o-notch"><i class="fa fa-circle-o-notch"></i></a></div>
            <div class="fa-hover"><a href="#fa-circle-thin"><i class="fa fa-circle-thin"></i></a></div>
            <div class="fa-hover"><a href="#fa-clock-o"><i class="fa fa-clock-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-times"><i class="fa fa-close"></i></a></div>
            <div class="fa-hover"><a href="#fa-cloud"><i class="fa fa-cloud"></i></a></div>
            <div class="fa-hover"><a href="#fa-cloud-download"><i class="fa fa-cloud-download"></i></a></div>
            <div class="fa-hover"><a href="#fa-cloud-upload"><i class="fa fa-cloud-upload"></i></a></div>
            <div class="fa-hover"><a href="#fa-code"><i class="fa fa-code"></i></a></div>
            <div class="fa-hover"><a href="#fa-code-fork"><i class="fa fa-code-fork"></i></a></div>
            <div class="fa-hover"><a href="#fa-coffee"><i class="fa fa-coffee"></i></a></div>
            <div class="fa-hover"><a href="#fa-cog"><i class="fa fa-cog"></i></a></div>
            <div class="fa-hover"><a href="#fa-cogs"><i class="fa fa-cogs"></i></a></div>
            <div class="fa-hover"><a href="#fa-comment"><i class="fa fa-comment"></i></a></div>
            <div class="fa-hover"><a href="#fa-comment-o"><i class="fa fa-comment-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-comments"><i class="fa fa-comments"></i></a></div>
            <div class="fa-hover"><a href="#fa-comments-o"><i class="fa fa-comments-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-compass"><i class="fa fa-compass"></i></a></div>
            <div class="fa-hover"><a href="#fa-copyright"><i class="fa fa-copyright"></i></a></div>
            <div class="fa-hover"><a href="#fa-credit-card"><i class="fa fa-credit-card"></i></a></div>
            <div class="fa-hover"><a href="#fa-crop"><i class="fa fa-crop"></i></a></div>
            <div class="fa-hover"><a href="#fa-crosshairs"><i class="fa fa-crosshairs"></i></a></div>
            <div class="fa-hover"><a href="#fa-cube"><i class="fa fa-cube"></i></a></div>
            <div class="fa-hover"><a href="#fa-cubes"><i class="fa fa-cubes"></i></a></div>
            <div class="fa-hover"><a href="#fa-cutlery"><i class="fa fa-cutlery"></i></a></div>
            <div class="fa-hover"><a href="#fa-tachometer"><i class="fa fa-dashboard"></i></a></div>
            <div class="fa-hover"><a href="#fa-database"><i class="fa fa-database"></i></a></div>
            <div class="fa-hover"><a href="#fa-desktop"><i class="fa fa-desktop"></i></a></div>
            <div class="fa-hover"><a href="#fa-diamond"><i class="fa fa-diamond"></i></a></div>
            <div class="fa-hover"><a href="#fa-dot-circle-o"><i class="fa fa-dot-circle-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-download"><i class="fa fa-download"></i></a></div>
            <div class="fa-hover"><a href="#fa-pencil-square-o"><i class="fa fa-edit"></i></a></div>
            <div class="fa-hover"><a href="#fa-ellipsis-h"><i class="fa fa-ellipsis-h"></i></a></div>
            <div class="fa-hover"><a href="#fa-ellipsis-v"><i class="fa fa-ellipsis-v"></i></a></div>
            <div class="fa-hover"><a href="#fa-envelope"><i class="fa fa-envelope"></i></a></div>
            <div class="fa-hover"><a href="#fa-envelope-o"><i class="fa fa-envelope-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-envelope-square"><i class="fa fa-envelope-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-eraser"><i class="fa fa-eraser"></i></a></div>
            <div class="fa-hover"><a href="#fa-exchange"><i class="fa fa-exchange"></i></a></div>
            <div class="fa-hover"><a href="#fa-exclamation"><i class="fa fa-exclamation"></i></a></div>
            <div class="fa-hover"><a href="#fa-exclamation-circle"><i class="fa fa-exclamation-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-exclamation-triangle"><i class="fa fa-exclamation-triangle"></i></a></div>
            <div class="fa-hover"><a href="#fa-external-link"><i class="fa fa-external-link"></i></a></div>
            <div class="fa-hover"><a href="#fa-external-link-square"><i class="fa fa-external-link-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-eye"><i class="fa fa-eye"></i></a></div>
            <div class="fa-hover"><a href="#fa-eye-slash"><i class="fa fa-eye-slash"></i></a></div>
            <div class="fa-hover"><a href="#fa-eyedropper"><i class="fa fa-eyedropper"></i></a></div>
            <div class="fa-hover"><a href="#fa-fax"><i class="fa fa-fax"></i></a></div>
            <div class="fa-hover"><a href="#fa-female"><i class="fa fa-female"></i></a></div>
            <div class="fa-hover"><a href="#fa-fighter-jet"><i class="fa fa-fighter-jet"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-archive-o"><i class="fa fa-file-archive-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-audio-o"><i class="fa fa-file-audio-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-code-o"><i class="fa fa-file-code-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-excel-o"><i class="fa fa-file-excel-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-image-o"><i class="fa fa-file-image-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-video-o"><i class="fa fa-file-movie-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-pdf-o"><i class="fa fa-file-pdf-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-image-o"><i class="fa fa-file-photo-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-image-o"><i class="fa fa-file-picture-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-powerpoint-o"><i class="fa fa-file-powerpoint-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-audio-o"><i class="fa fa-file-sound-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-video-o"><i class="fa fa-file-video-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-word-o"><i class="fa fa-file-word-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-file-archive-o"><i class="fa fa-file-zip-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-film"><i class="fa fa-film"></i></a></div>
            <div class="fa-hover"><a href="#fa-filter"><i class="fa fa-filter"></i></a></div>
            <div class="fa-hover"><a href="#fa-fire"><i class="fa fa-fire"></i></a></div>
            <div class="fa-hover"><a href="#fa-fire-extinguisher"><i class="fa fa-fire-extinguisher"></i></a></div>
            <div class="fa-hover"><a href="#fa-flag"><i class="fa fa-flag"></i></a></div>
            <div class="fa-hover"><a href="#fa-flag-checkered"><i class="fa fa-flag-checkered"></i></a></div>
            <div class="fa-hover"><a href="#fa-flag-o"><i class="fa fa-flag-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-bolt"><i class="fa fa-flash"></i></a></div>
            <div class="fa-hover"><a href="#fa-flask"><i class="fa fa-flask"></i></a></div>
            <div class="fa-hover"><a href="#fa-folder"><i class="fa fa-folder"></i></a></div>
            <div class="fa-hover"><a href="#fa-folder-o"><i class="fa fa-folder-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-folder-open"><i class="fa fa-folder-open"></i></a></div>
            <div class="fa-hover"><a href="#fa-folder-open-o"><i class="fa fa-folder-open-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-frown-o"><i class="fa fa-frown-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-futbol-o"><i class="fa fa-futbol-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-gamepad"><i class="fa fa-gamepad"></i></a></div>
            <div class="fa-hover"><a href="#fa-gavel"><i class="fa fa-gavel"></i></a></div>
            <div class="fa-hover"><a href="#fa-cog"><i class="fa fa-gear"></i></a></div>
            <div class="fa-hover"><a href="#fa-cogs"><i class="fa fa-gears"></i></a></div>
            <div class="fa-hover"><a href="#fa-circle-thin"><i class="fa fa-genderless"></i></a></div>
            <div class="fa-hover"><a href="#fa-gift"><i class="fa fa-gift"></i></a></div>
            <div class="fa-hover"><a href="#fa-glass"><i class="fa fa-glass"></i></a></div>
            <div class="fa-hover"><a href="#fa-globe"><i class="fa fa-globe"></i></a></div>
            <div class="fa-hover"><a href="#fa-graduation-cap"><i class="fa fa-graduation-cap"></i></a></div>
            <div class="fa-hover"><a href="#fa-users"><i class="fa fa-group"></i></a></div>
            <div class="fa-hover"><a href="#fa-hdd-o"><i class="fa fa-hdd-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-headphones"><i class="fa fa-headphones"></i></a></div>
            <div class="fa-hover"><a href="#fa-heart"><i class="fa fa-heart"></i></a></div>
            <div class="fa-hover"><a href="#fa-heart-o"><i class="fa fa-heart-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-heartbeat"><i class="fa fa-heartbeat"></i></a></div>
            <div class="fa-hover"><a href="#fa-history"><i class="fa fa-history"></i></a></div>
            <div class="fa-hover"><a href="#fa-home"><i class="fa fa-home"></i></a></div>
            <div class="fa-hover"><a href="#fa-bed"><i class="fa fa-hotel"></i></a></div>
            <div class="fa-hover"><a href="#fa-picture-o"><i class="fa fa-image"></i></a></div>
            <div class="fa-hover"><a href="#fa-inbox"><i class="fa fa-inbox"></i></a></div>
            <div class="fa-hover"><a href="#fa-info"><i class="fa fa-info"></i></a></div>
            <div class="fa-hover"><a href="#fa-info-circle"><i class="fa fa-info-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-university"><i class="fa fa-institution"></i></a></div>
            <div class="fa-hover"><a href="#fa-key"><i class="fa fa-key"></i></a></div>
            <div class="fa-hover"><a href="#fa-keyboard-o"><i class="fa fa-keyboard-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-language"><i class="fa fa-language"></i></a></div>
            <div class="fa-hover"><a href="#fa-laptop"><i class="fa fa-laptop"></i></a></div>
            <div class="fa-hover"><a href="#fa-leaf"><i class="fa fa-leaf"></i></a></div>
            <div class="fa-hover"><a href="#fa-gavel"><i class="fa fa-legal"></i></a></div>
            <div class="fa-hover"><a href="#fa-lemon-o"><i class="fa fa-lemon-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-level-down"><i class="fa fa-level-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-level-up"><i class="fa fa-level-up"></i></a></div>
            <div class="fa-hover"><a href="#fa-life-ring"><i class="fa fa-life-bouy"></i></a></div>
            <div class="fa-hover"><a href="#fa-life-ring"><i class="fa fa-life-buoy"></i></a></div>
            <div class="fa-hover"><a href="#fa-life-ring"><i class="fa fa-life-ring"></i></a></div>
            <div class="fa-hover"><a href="#fa-life-ring"><i class="fa fa-life-saver"></i></a></div>
            <div class="fa-hover"><a href="#fa-lightbulb-o"><i class="fa fa-lightbulb-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-line-chart"><i class="fa fa-line-chart"></i></a></div>
            <div class="fa-hover"><a href="#fa-location-arrow"><i class="fa fa-location-arrow"></i></a></div>
            <div class="fa-hover"><a href="#fa-lock"><i class="fa fa-lock"></i></a></div>
            <div class="fa-hover"><a href="#fa-magic"><i class="fa fa-magic"></i></a></div>
            <div class="fa-hover"><a href="#fa-magnet"><i class="fa fa-magnet"></i></a></div>
            <div class="fa-hover"><a href="#fa-share"><i class="fa fa-mail-forward"></i></a></div>
            <div class="fa-hover"><a href="#fa-reply"><i class="fa fa-mail-reply"></i></a></div>
            <div class="fa-hover"><a href="#fa-reply-all"><i class="fa fa-mail-reply-all"></i></a></div>
            <div class="fa-hover"><a href="#fa-male"><i class="fa fa-male"></i></a></div>
            <div class="fa-hover"><a href="#fa-map-marker"><i class="fa fa-map-marker"></i></a></div>
            <div class="fa-hover"><a href="#fa-meh-o"><i class="fa fa-meh-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-microphone"><i class="fa fa-microphone"></i></a></div>
            <div class="fa-hover"><a href="#fa-microphone-slash"><i class="fa fa-microphone-slash"></i></a></div>
            <div class="fa-hover"><a href="#fa-minus"><i class="fa fa-minus"></i></a></div>
            <div class="fa-hover"><a href="#fa-minus-circle"><i class="fa fa-minus-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-minus-square"><i class="fa fa-minus-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-minus-square-o"><i class="fa fa-minus-square-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-mobile"><i class="fa fa-mobile"></i></a></div>
            <div class="fa-hover"><a href="#fa-mobile"><i class="fa fa-mobile-phone"></i></a></div>
            <div class="fa-hover"><a href="#fa-money"><i class="fa fa-money"></i></a></div>
            <div class="fa-hover"><a href="#fa-moon-o"><i class="fa fa-moon-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-graduation-cap"><i class="fa fa-mortar-board"></i></a></div>
            <div class="fa-hover"><a href="#fa-motorcycle"><i class="fa fa-motorcycle"></i></a></div>
            <div class="fa-hover"><a href="#fa-music"><i class="fa fa-music"></i></a></div>
            <div class="fa-hover"><a href="#fa-bars"><i class="fa fa-navicon"></i></a></div>
            <div class="fa-hover"><a href="#fa-newspaper-o"><i class="fa fa-newspaper-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-paint-brush"><i class="fa fa-paint-brush"></i></a></div>
            <div class="fa-hover"><a href="#fa-paper-plane"><i class="fa fa-paper-plane"></i></a></div>
            <div class="fa-hover"><a href="#fa-paper-plane-o"><i class="fa fa-paper-plane-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-paw"><i class="fa fa-paw"></i></a></div>
            <div class="fa-hover"><a href="#fa-pencil"><i class="fa fa-pencil"></i></a></div>
            <div class="fa-hover"><a href="#fa-pencil-square"><i class="fa fa-pencil-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-pencil-square-o"><i class="fa fa-pencil-square-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-phone"><i class="fa fa-phone"></i></a></div>
            <div class="fa-hover"><a href="#fa-phone-square"><i class="fa fa-phone-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-picture-o"><i class="fa fa-photo"></i></a></div>
            <div class="fa-hover"><a href="#fa-picture-o"><i class="fa fa-picture-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-pie-chart"><i class="fa fa-pie-chart"></i></a></div>
            <div class="fa-hover"><a href="#fa-plane"><i class="fa fa-plane"></i></a></div>
            <div class="fa-hover"><a href="#fa-plug"><i class="fa fa-plug"></i></a></div>
            <div class="fa-hover"><a href="#fa-plus"><i class="fa fa-plus"></i></a></div>
            <div class="fa-hover"><a href="#fa-plus-circle"><i class="fa fa-plus-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-plus-square"><i class="fa fa-plus-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-plus-square-o"><i class="fa fa-plus-square-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-power-off"><i class="fa fa-power-off"></i></a></div>
            <div class="fa-hover"><a href="#fa-print"><i class="fa fa-print"></i></a></div>
            <div class="fa-hover"><a href="#fa-puzzle-piece"><i class="fa fa-puzzle-piece"></i></a></div>
            <div class="fa-hover"><a href="#fa-qrcode"><i class="fa fa-qrcode"></i></a></div>
            <div class="fa-hover"><a href="#fa-question"><i class="fa fa-question"></i></a></div>
            <div class="fa-hover"><a href="#fa-question-circle"><i class="fa fa-question-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-quote-left"><i class="fa fa-quote-left"></i></a></div>
            <div class="fa-hover"><a href="#fa-quote-right"><i class="fa fa-quote-right"></i></a></div>
            <div class="fa-hover"><a href="#fa-random"><i class="fa fa-random"></i></a></div>
            <div class="fa-hover"><a href="#fa-recycle"><i class="fa fa-recycle"></i></a></div>
            <div class="fa-hover"><a href="#fa-refresh"><i class="fa fa-refresh"></i></a></div>
            <div class="fa-hover"><a href="#fa-times"><i class="fa fa-remove"></i></a></div>
            <div class="fa-hover"><a href="#fa-bars"><i class="fa fa-reorder"></i></a></div>
            <div class="fa-hover"><a href="#fa-reply"><i class="fa fa-reply"></i></a></div>
            <div class="fa-hover"><a href="#fa-reply-all"><i class="fa fa-reply-all"></i></a></div>
            <div class="fa-hover"><a href="#fa-retweet"><i class="fa fa-retweet"></i></a></div>
            <div class="fa-hover"><a href="#fa-road"><i class="fa fa-road"></i></a></div>
            <div class="fa-hover"><a href="#fa-rocket"><i class="fa fa-rocket"></i></a></div>
            <div class="fa-hover"><a href="#fa-rss"><i class="fa fa-rss"></i></a></div>
            <div class="fa-hover"><a href="#fa-rss-square"><i class="fa fa-rss-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-search"><i class="fa fa-search"></i></a></div>
            <div class="fa-hover"><a href="#fa-search-minus"><i class="fa fa-search-minus"></i></a></div>
            <div class="fa-hover"><a href="#fa-search-plus"><i class="fa fa-search-plus"></i></a></div>
            <div class="fa-hover"><a href="#fa-paper-plane"><i class="fa fa-send"></i></a></div>
            <div class="fa-hover"><a href="#fa-paper-plane-o"><i class="fa fa-send-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-server"><i class="fa fa-server"></i></a></div>
            <div class="fa-hover"><a href="#fa-share"><i class="fa fa-share"></i></a></div>
            <div class="fa-hover"><a href="#fa-share-alt"><i class="fa fa-share-alt"></i></a></div>
            <div class="fa-hover"><a href="#fa-share-alt-square"><i class="fa fa-share-alt-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-share-square"><i class="fa fa-share-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-share-square-o"><i class="fa fa-share-square-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-shield"><i class="fa fa-shield"></i></a></div>
            <div class="fa-hover"><a href="#fa-ship"><i class="fa fa-ship"></i></a></div>
            <div class="fa-hover"><a href="#fa-shopping-cart"><i class="fa fa-shopping-cart"></i></a></div>
            <div class="fa-hover"><a href="#fa-sign-in"><i class="fa fa-sign-in"></i></a></div>
            <div class="fa-hover"><a href="#fa-sign-out"><i class="fa fa-sign-out"></i></a></div>
            <div class="fa-hover"><a href="#fa-signal"><i class="fa fa-signal"></i></a></div>
            <div class="fa-hover"><a href="#fa-sitemap"><i class="fa fa-sitemap"></i></a></div>
            <div class="fa-hover"><a href="#fa-sliders"><i class="fa fa-sliders"></i></a></div>
            <div class="fa-hover"><a href="#fa-smile-o"><i class="fa fa-smile-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-futbol-o"><i class="fa fa-soccer-ball-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort"><i class="fa fa-sort"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-alpha-asc"><i class="fa fa-sort-alpha-asc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-alpha-desc"><i class="fa fa-sort-alpha-desc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-amount-asc"><i class="fa fa-sort-amount-asc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-amount-desc"><i class="fa fa-sort-amount-desc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-asc"><i class="fa fa-sort-asc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-desc"><i class="fa fa-sort-desc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-desc"><i class="fa fa-sort-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-numeric-asc"><i class="fa fa-sort-numeric-asc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-numeric-desc"><i class="fa fa-sort-numeric-desc"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort-asc"><i class="fa fa-sort-up"></i></a></div>
            <div class="fa-hover"><a href="#fa-space-shuttle"><i class="fa fa-space-shuttle"></i></a></div>
            <div class="fa-hover"><a href="#fa-spinner"><i class="fa fa-spinner"></i></a></div>
            <div class="fa-hover"><a href="#fa-spoon"><i class="fa fa-spoon"></i></a></div>
            <div class="fa-hover"><a href="#fa-square"><i class="fa fa-square"></i></a></div>
            <div class="fa-hover"><a href="#fa-square-o"><i class="fa fa-square-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-star"><i class="fa fa-star"></i></a></div>
            <div class="fa-hover"><a href="#fa-star-half"><i class="fa fa-star-half"></i></a></div>
            <div class="fa-hover"><a href="#fa-star-half-o"><i class="fa fa-star-half-empty"></i></a></div>
            <div class="fa-hover"><a href="#fa-star-half-o"><i class="fa fa-star-half-full"></i></a></div>
            <div class="fa-hover"><a href="#fa-star-half-o"><i class="fa fa-star-half-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-star-o"><i class="fa fa-star-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-street-view"><i class="fa fa-street-view"></i></a></div>
            <div class="fa-hover"><a href="#fa-suitcase"><i class="fa fa-suitcase"></i></a></div>
            <div class="fa-hover"><a href="#fa-sun-o"><i class="fa fa-sun-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-life-ring"><i class="fa fa-support"></i></a></div>
            <div class="fa-hover"><a href="#fa-tablet"><i class="fa fa-tablet"></i></a></div>
            <div class="fa-hover"><a href="#fa-tachometer"><i class="fa fa-tachometer"></i></a></div>
            <div class="fa-hover"><a href="#fa-tag"><i class="fa fa-tag"></i></a></div>
            <div class="fa-hover"><a href="#fa-tags"><i class="fa fa-tags"></i></a></div>
            <div class="fa-hover"><a href="#fa-tasks"><i class="fa fa-tasks"></i></a></div>
            <div class="fa-hover"><a href="#fa-taxi"><i class="fa fa-taxi"></i></a></div>
            <div class="fa-hover"><a href="#fa-terminal"><i class="fa fa-terminal"></i></a></div>
            <div class="fa-hover"><a href="#fa-thumb-tack"><i class="fa fa-thumb-tack"></i></a></div>
            <div class="fa-hover"><a href="#fa-thumbs-down"><i class="fa fa-thumbs-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-thumbs-o-down"><i class="fa fa-thumbs-o-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-thumbs-o-up"><i class="fa fa-thumbs-o-up"></i></a></div>
            <div class="fa-hover"><a href="#fa-thumbs-up"><i class="fa fa-thumbs-up"></i></a></div>
            <div class="fa-hover"><a href="#fa-ticket"><i class="fa fa-ticket"></i></a></div>
            <div class="fa-hover"><a href="#fa-times"><i class="fa fa-times"></i></a></div>
            <div class="fa-hover"><a href="#fa-times-circle"><i class="fa fa-times-circle"></i></a></div>
            <div class="fa-hover"><a href="#fa-times-circle-o"><i class="fa fa-times-circle-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-tint"><i class="fa fa-tint"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-down"><i class="fa fa-toggle-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-left"><i class="fa fa-toggle-left"></i></a></div>
            <div class="fa-hover"><a href="#fa-toggle-off"><i class="fa fa-toggle-off"></i></a></div>
            <div class="fa-hover"><a href="#fa-toggle-on"><i class="fa fa-toggle-on"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-right"><i class="fa fa-toggle-right"></i></a></div>
            <div class="fa-hover"><a href="#fa-caret-square-o-up"><i class="fa fa-toggle-up"></i></a></div>
            <div class="fa-hover"><a href="#fa-trash"><i class="fa fa-trash"></i></a></div>
            <div class="fa-hover"><a href="#fa-trash-o"><i class="fa fa-trash-o"></i></a></div>
            <div class="fa-hover"><a href="#fa-tree"><i class="fa fa-tree"></i></a></div>
            <div class="fa-hover"><a href="#fa-trophy"><i class="fa fa-trophy"></i></a></div>
            <div class="fa-hover"><a href="#fa-truck"><i class="fa fa-truck"></i></a></div>
            <div class="fa-hover"><a href="#fa-tty"><i class="fa fa-tty"></i></a></div>
            <div class="fa-hover"><a href="#fa-umbrella"><i class="fa fa-umbrella"></i></a></div>
            <div class="fa-hover"><a href="#fa-university"><i class="fa fa-university"></i></a></div>
            <div class="fa-hover"><a href="#fa-unlock"><i class="fa fa-unlock"></i></a></div>
            <div class="fa-hover"><a href="#fa-unlock-alt"><i class="fa fa-unlock-alt"></i></a></div>
            <div class="fa-hover"><a href="#fa-sort"><i class="fa fa-unsorted"></i></a></div>
            <div class="fa-hover"><a href="#fa-upload"><i class="fa fa-upload"></i></a></div>
            <div class="fa-hover"><a href="#fa-user"><i class="fa fa-user"></i></a></div>
            <div class="fa-hover"><a href="#fa-user-plus"><i class="fa fa-user-plus"></i></a></div>
            <div class="fa-hover"><a href="#fa-user-secret"><i class="fa fa-user-secret"></i></a></div>
            <div class="fa-hover"><a href="#fa-user-times"><i class="fa fa-user-times"></i></a></div>
            <div class="fa-hover"><a href="#fa-users"><i class="fa fa-users"></i></a></div>
            <div class="fa-hover"><a href="#fa-video-camera"><i class="fa fa-video-camera"></i></a></div>
            <div class="fa-hover"><a href="#fa-volume-down"><i class="fa fa-volume-down"></i></a></div>
            <div class="fa-hover"><a href="#fa-volume-off"><i class="fa fa-volume-off"></i></a></div>
            <div class="fa-hover"><a href="#fa-volume-up"><i class="fa fa-volume-up"></i></a></div>
            <div class="fa-hover"><a href="#fa-exclamation-triangle"><i class="fa fa-warning"></i></a></div>
            <div class="fa-hover"><a href="#fa-wheelchair"><i class="fa fa-wheelchair"></i></a></div>
            <div class="fa-hover"><a href="#fa-wifi"><i class="fa fa-wifi"></i></a></div>
            <div class="fa-hover"><a href="#fa-wrench"><i class="fa fa-wrench"></i></a></div>
         </div>
      </section>

		<?php
			/*
			* Action hook to add more icons
			*/
			do_action( 'pt_pb_after_fa_icons' );
		?>

   </div>
</div>